# Generated by Django 5.0.6 on 2024-06-15 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe_wizard', '0004_alter_photo_photo_lower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='cloths'),
        ),
        migrations.DeleteModel(
            name='Lower',
        ),
    ]
