# Generated by Django 5.0.6 on 2024-06-23 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe_wizard', '0008_lower'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingCombination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wardrobe_wizard.lower')),
                ('upper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wardrobe_wizard.upper')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
