# Generated by Django 5.0.6 on 2024-06-23 07:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe_wizard', '0009_matchingcombination'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matchingcombination',
            unique_together={('user', 'upper', 'lower')},
        ),
    ]
