# Generated by Django 5.0.6 on 2024-06-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe_wizard', '0010_alter_matchingcombination_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lower',
            name='lower',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='upper',
            name='upper',
            field=models.ImageField(upload_to=''),
        ),
    ]
